# These are supported funding model platforms

patreon: bezierinfo
custom: ['https://www.paypal.com/donate/?business=PVFNX2EG6HFFG&no_recurring=0&item_name=Sponsor+Pomax%27s+free+online+content%21&currency_code=CAD']
