name: Continuous Integration Testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test_first_time_setup:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo rm /var/lib/man-db/auto-update
          sudo apt-get install -y caddy sqlite3 curl

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run first time setup
        run: |
          cp .env.ci .env
          npm install
          node setup --no-auth --no-tls
